<main>
      <section>
      <header>
          <h2>Ajouter une catégorie</h1>
      </header>
       
            
    <form action="/res03-auth/check-creer-categorie" method="post">
      <label for="nom">Nom de la catégorie :</label>
            <input type="text" name="nom" id="nom" required>
      <label for="description">Description :</label>
            <textarea name="description" id="description"></textarea>
      <footer>
            <input type="submit" value="Ajouter la catégorie">
      </footer>
    </form>
    </section>
</main>